# Generated by Django 3.2 on 2021-07-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('p_date', models.DateTimeField()),
                ('contents', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='book/')),
            ],
        ),
    ]
